name: GitHub Actions - System Requirements
## on: [push]
on:
####----------------------------------------------------------------------------
  workflow_dispatch:
    name: 'Manual Deployment'
    description: 'Triggering Manual Deployment'
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'System Requirements'
####----------------------------------------------------------------------------
  push:
    branches: [ master ]
    paths:
      - action.yaml
      - '*.request'
####----------------------------------------------------------------------------
##  env:
####----------------------------------------------------------------------------
jobs:
  system-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
####----------------------------------------------------------------------------
      ## System Requirements
      - name: System Requirements
        uses: ./
        id: system-requirements
        with:
          install-awscli-tool: true
          # install-custom-tools: 'netcat'
          # install-default-tools: true
          install-terraform-cli: true
          # update-operating-system: true
          update-python-version: true
        continue-on-error: false
      - name: Check On Failures
        if: steps.system-requirements.outputs.status == 'failure'
        run: |
          echo -e "Warning: System Requirements Failed [Status]: ${{ steps.system-requirements.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## Installed Packages
      - name: Installed Packages
        id: installed-packages
        shell: bash
        run: |
          jq --version 2>/dev/null ;
          terraform --version 2>/dev/null ;
